const CONSTANT_AUTHENTICATE = {

    // Login
    SIGNIN_REQUESTED: 'SIGNIN_REQUESTED',
    SIGNIN_SUCCEEDED: 'SIGNIN_SUCCEEDED',
    SIGNIN_FAILED: 'SIGNIN_FAILED',

    // LOGOUT
    LOGOUT_REQUESTED: 'LOGOUT_REQUESTED',
    LOGOUT_SUCCEEDED: 'LOGOUT_SUCCEEDED',
    LOGOUT_FAILED: 'LOGOUT_FAILED',
};

export default CONSTANT_AUTHENTICATE;